version: '3'
services:
  api:
    build: .
    depends_on:
      - forgettable
      - postgresql
      - redis
    environment:
      - DATABASE_URL=postgresql://mm:mm@postgresql/mm
    env_file: .env
    volumes:
      - ./server.js:/opt/app/server.js
      - ./db:/opt/app/db
      - ./models:/opt/app/models
      - ./routes:/opt/app/routes
    ports:
      - "3000:3000"
    links:
      - forgettable
      - postgresql
      - redis
    command: nodemon server.js
  forgettable:
    build: forgettable
    depends_on:
      - redis
    links:
      - redis
  redis:
    image: redis
  postgresql:
    image: mdillon/postgis:9.6
    environment:
      - POSTGRES_USER=mm
      - POSTGRES_PASSWORD=mm
      - POSTGRES_DB=mm
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
